/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package systems.tech247.dbaccess;

import java.sql.Connection;
import java.sql.DriverManager;
import java.util.Properties;
import org.openide.LifecycleManager;
import org.openide.util.NbPreferences;

final class DatabaseSettingsPanel extends javax.swing.JPanel {

    private final DatabaseConnectionSettingsOptionsPanelController controller;

    DatabaseSettingsPanel(DatabaseConnectionSettingsOptionsPanelController controller) {
        this.controller = controller;
        initComponents();
        // TODO listen to changes in form fields and call controller.changed()
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtServerName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtDBName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtPortNumber = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtUsername = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jpPassword = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        lblTest = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(DatabaseSettingsPanel.class, "DatabaseSettingsPanel.jLabel1.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(DatabaseSettingsPanel.class, "DatabaseSettingsPanel.jLabel2.text")); // NOI18N

        jtServerName.setText(org.openide.util.NbBundle.getMessage(DatabaseSettingsPanel.class, "DatabaseSettingsPanel.jtServerName.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(DatabaseSettingsPanel.class, "DatabaseSettingsPanel.jLabel3.text")); // NOI18N

        jtDBName.setText(org.openide.util.NbBundle.getMessage(DatabaseSettingsPanel.class, "DatabaseSettingsPanel.jtDBName.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(DatabaseSettingsPanel.class, "DatabaseSettingsPanel.jLabel4.text")); // NOI18N

        jtPortNumber.setText(org.openide.util.NbBundle.getMessage(DatabaseSettingsPanel.class, "DatabaseSettingsPanel.jtPortNumber.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel5, org.openide.util.NbBundle.getMessage(DatabaseSettingsPanel.class, "DatabaseSettingsPanel.jLabel5.text")); // NOI18N

        jtUsername.setText(org.openide.util.NbBundle.getMessage(DatabaseSettingsPanel.class, "DatabaseSettingsPanel.jtUsername.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel6, org.openide.util.NbBundle.getMessage(DatabaseSettingsPanel.class, "DatabaseSettingsPanel.jLabel6.text")); // NOI18N

        jpPassword.setText(org.openide.util.NbBundle.getMessage(DatabaseSettingsPanel.class, "DatabaseSettingsPanel.jpPassword.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jButton1, org.openide.util.NbBundle.getMessage(DatabaseSettingsPanel.class, "DatabaseSettingsPanel.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(lblTest, org.openide.util.NbBundle.getMessage(DatabaseSettingsPanel.class, "DatabaseSettingsPanel.lblTest.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtServerName, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                    .addComponent(jtDBName, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                    .addComponent(jtPortNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                    .addComponent(jtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                    .addComponent(jpPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 76, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jpPassword, jtDBName, jtPortNumber, jtServerName, jtUsername});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtServerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtDBName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtPortNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jpPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addComponent(lblTest)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String connectionUrl = "jdbc:sqlserver://"+
                jtServerName.getText()+":"+
                jtPortNumber.getText()+";databaseName="+
                jtDBName.getText()+";user="+
                jtUsername.getText()+";password="+
                jpPassword.getText();
        
        Connection con =  null;
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            con = DriverManager.getConnection(connectionUrl);
            Properties p=con.getClientInfo();
            lblTest.setText("Connected");
        }catch(Exception ex){
            lblTest.setText(/*ex.getLocalizedMessage()+*/"  Url:"+connectionUrl);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    void load() {
        // Retrieve the server name
        jtServerName.setText(NbPreferences.forModule(DatabaseSettingsPanel.class).get("DBServerName", ""));
        // Retrieve the login name
        jtUsername.setText(NbPreferences.forModule(DatabaseSettingsPanel.class).get("DBLogin", ""));
        // Get the Password
        jpPassword.setText(NbPreferences.forModule(DatabaseSettingsPanel.class).get("DBPassword", ""));
        // Get Server Port
        jtPortNumber.setText(NbPreferences.forModule(DatabaseSettingsPanel.class).get("DBPort", ""));
        // Get DBName
        jtDBName.setText(NbPreferences.forModule(DatabaseSettingsPanel.class).get("DBName", ""));
    }

    void store() {
        // TODO store modified settings
        // Example:
        // Preferences.userNodeForPackage(DatabaseConnectionSettingsPanel.class).putBoolean("someFlag", someCheckBox.isSelected());
        // or for org.openide.util with API spec. version >= 7.4:
        // NbPreferences.forModule(DatabaseConnectionSettingsPanel.class).putBoolean("someFlag", someCheckBox.isSelected());
        // or:
        // SomeSystemOption.getDefault().setSomeStringProperty(someTextField.getText());
        NbPreferences.forModule(DatabaseSettingsPanel.class).put("DBServerName", jtServerName.getText());
        NbPreferences.forModule(DatabaseSettingsPanel.class).put("DBLogin", jtUsername.getText());
        NbPreferences.forModule(DatabaseSettingsPanel.class).put("DBPassword", jpPassword.getText());
        NbPreferences.forModule(DatabaseSettingsPanel.class).put("DBPort", jtPortNumber.getText());
        NbPreferences.forModule(DatabaseSettingsPanel.class).put("DBName", jtDBName.getText());
        
        LifecycleManager.getDefault().markForRestart();
        LifecycleManager.getDefault().exit();
    }

    boolean valid() {
        // TODO check whether form is consistent and complete
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField jpPassword;
    private javax.swing.JTextField jtDBName;
    private javax.swing.JTextField jtPortNumber;
    private javax.swing.JTextField jtServerName;
    private javax.swing.JTextField jtUsername;
    private javax.swing.JLabel lblTest;
    // End of variables declaration//GEN-END:variables
}
